name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build library
      run: ./gradlew lib:build
    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: unit-test-reports
        path: lib/build/reports/tests/
    - name: Run functional tests
      run: ./gradlew functionalTests:test
    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: funct-test-reports
        path: functionalTests/build/reports/tests/

